### ISSUE TITLE
Update for Grade-10-Unit-1

### ISSUE THREAD

**Issue by rodneylg** [DCPSCanvas/Grade-10-Unit-1#2]
In the index file, you will find updated code for Grade-10-Unit-1

<Line 181>The unit banner was updated to reflect content from grade 10, unit 1
<Line 224>Paragraph was updated to reflect content
<Line 242>Wording updated
<Line 244-245>Bullet points lists reflects unit content
<Line 255-256>Bullet points lists reflects unit content 
<Line 286-301>Content reflects CCSS.  "<d1>" tags were duplicated from existing code, then edited to reflect necessary standards
<Line 304-318>Content reflects CCSS.  "<d1>" tags were duplicated from existing code,  then edited to reflect necessary standards
<Line 310-344>Content reflects CCSS.  "<d1>" tags were duplicated from existing code,  then edited to reflect necessary standards
<Line 347-362>Content reflects CCSS.  "<d1>" tags were duplicated from existing code,  then edited to reflect necessary standards" tags were duplicated from existing code,  then edited to reflect necessary standards
<Line 372-379>Content reflects CCSS.  "<d1>" tags were duplicated from existing code,  then edited to reflect necessary standards" tags were duplicated from existing code,  then edited to reflect necessary standards
<Line 382-401>Content reflects CCSS.  "<d1>" tags were duplicated from existing code,  then edited to reflect necessary standards" tags were duplicated from existing code,  then edited to reflect necessary standards
<Line 411-432>Content reflects CCSS.  "<d1>" tags were duplicated from existing code,  then edited to reflect necessary standards" tags were duplicated from existing code,  then edited to reflect necessary standards
<Line 442-457>Content reflects CCSS.  "<d1>" tags were duplicated from existing code,  then edited to reflect necessary standards" tags were duplicated from existing code,  then edited to reflect necessary standards
<Line 459-475>Content reflects CCSS.  "<d1>" tags were duplicated from existing code,  then edited to reflect necessary standards" tags were duplicated from existing code,  then edited to reflect necessary standards
<Line 803>heading changed to "Topic Information"
<Line 804>Paragraph added to reflect content in the unit guide
<Line 805>line break added
<Line 806>Paragraph added to reflect content in the unit guide
<Line 808-811>Bullet points added to reflect content in unit guide. link tags were added for websites 
<Line 814> heading changed to "Genre information "
<Line 816-817>Bullet points added to reflect content in unit guide
<Line 819>heading changed to "resources"
<Line 822>Bullet points added to reflect content in unit guide
<Line 823-827>Embed bullet points were added to resemeble unit guide formatting.  
<824>link tag was added

**Comment by JeremyLykken** [comment]
@rodneylg I reviewed your Pull Request. You can view my comments for the changes there.
